print("hello")
print("What is your name?")
myname=input()
print("It is good to meet you," +myname)
print("length of your name")
print(len(myname))
print("What is your age?")
age=input()
print("You will be " + str(int(age)+1)+ " in a year.")
